### PR TITLE
Make most resource values already defined by a template optional

### PR DESCRIPTION
**Pull request by fstern**
This makes most options for the opennebula_vm resource optional, as a lot of those can already be defined by the template. 

Required options now are: 
* `count`
* `name`
* `template_id`
* `network` 
* `image`

Permissions now default to `640`.

This should cut resource definitions down a lot.

### CODE REVIEW

**Comment by gersilex** [comment]
Great to hear from you again! I will review and check up with the other maintainers on Monday. Thank you very much for your work!

**Comment by denniskribl** [comment]
Hey @fstern, thank you for your contribution. Really really appreciate it. Your PR looks good to me. 
@gersilex I've tested it in our infrastructure with the modules we created, we defined some defaults there so we should be safe if some dev decides to use a template which doesn't provide enough input. Lets have a talk later today and merge if everyone is fine with it

**Comment by gersilex** [comment]
Is there a specific reason why `network` and `image` are still required? If I get this right, they could also be part of the VM Template we specify in `template_id` and therefore be optional, couldn't they?

```text
# VM Template (excerpt)

DISK = [ IMAGE = "CentOS 7 - KVM" ]
NIC = [ NETWORK = "network1" ]
```

What do you guys think?

**Comment by fstern** [comment]
I kept `network` as a required option, because most templates from the marketplace don‘t include a template. 

`image` is required when specifying a `size`. Otherwise this data needs to be parsed out of the template and corresponding image.

**Comment by gersilex** [comment]
Makes sense, thanks. I ran some tests as well and the `terraform apply` fails gracefully when data is missing both in the Terraform Resource and the OpenNebula Template the Resource uses:

```text
* opennebula_vm.vm-base: [one.template.instantiate] User [14] : user [14] MEMORY attribute must be a positive integer value.
```

We also have a vocal "Go" from @cacar87 so I'm merging it right now. @fstern Thanks again. Also for cleaning up the `template` string builder in `resourceVmCreate()`!

**Pull request merged**
